### ISSUE TITLE
list_metrics ですべてのメトリクスが取得できていない

### ISSUE THREAD

**Issue by funakura222** [falco694/corrcloudwatch#5]

**Comment by funakura222** [comment]
> Up to 500 results are returned for any one call. To retrieve additional results, use the returned token with subsequent calls.

[CloudWatch — Boto 3 Docs 1.9.156 documentation](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/cloudwatch.html?highlight=list_metrics#CloudWatch.Client.list_metrics)

**Comment by funakura222** [comment]
合わせて、get_metric_dataの対応も行う。
[CloudWatch — Boto 3 Docs 1.9.156 documentation](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/cloudwatch.html?highlight=list_metrics#CloudWatch.Client.get_metric_data)

**Comment by falco694** [comment]
参考になりそうな記事
[Pythonについて vol08.Boto3 - Qiita](https://qiita.com/sachioksg/items/91cc589e7e00913abfbd)

```
ec2 = session.client('ec2')
token = ''

while token is not None:
    response = ec2.describe_instances(
        MaxResults=10,
        NextToken=token
    )
    for res in response['Reservations']:
        print(res['Instances'][0]['InstanceId'])

    if 'NextToken' in response:
        token = response['NextToken']
    else:
        token = None
```
